### ISSUE TITLE
populus chain run fails with latest geth 1.5.0

### ISSUE THREAD

**Issue by smoove** [pipermerriam/populus#103]
* Populus Version: 0.8.0
* OS: Ubuntu 16.04
* Geth: 1.5.0-unstable (current version from Ubuntu Repository)

### What was wrong?
`populus chain run` fails with 

> Command 'nice -n 20 geth --genesis /usr/local/lib/python2.7/dist-packages/populus/genesis-test.json [...]' returned non-zero exit status 1

running the generated geth command manually returns

> flag provided but not defined: -genesis

So apparently the "--genesis" flag was removed from geth.

#### Cute Animal Picture

![:)](http://memesvault.com/wp-content/uploads/Happy-Birthday-Meme-Dog-11.jpg)

**Comment by pipermerriam** [comment]
This will be fixed when #105 gets merged.
