### ISSUE TITLE
Make populus compile to accept input and output folders

### ISSUE THREAD

**Issue by miohtama** [pipermerriam/populus#108]
### What was wrong?

Currently `populus compile` makes assumptions about directory layout. It doesn't allow to set build folder target.

I want to use the following deployment model 
- `populus compile` to build .sol source
- `python setup.py sdist` to package my app
- Install application in its runtime environment
- On the application run-time, access `contracts.json` using `Python pkg_resources` mechanism 
- However `contracts.json` folder is generated in the current project root, not inside my package namespace where I'd like to place it for `sdist`. This is naturally easy to move.  I am not sure if this workflow is correct, just double checking here before suggesting a patch.
#### Cute Animal Picture

![deer](http://i.imgur.com/AXoNmhW.jpg)

**Comment by pipermerriam** [comment]
I like it.  How about three new flags.

1. --project-dir to specify project root. This would need to be used like
'populus --project-dir compile' as opposed to 'polulus compile
--project-dir'
2. --source-file to specify specific source files to include. This can be
used multiple times to specify multiple source files. Maybe allow glob
patterns as well.
3. --output to specify the path that compiled sources should be written to.

**Comment by pipermerriam** [comment]
Ok, this is now something that should be implemented on top of the `populus.ini` file and the new `populus.project.Project` API.

**Comment by pipermerriam** [comment]
Half of this (custom input folders) is now supported.  Custom output folders is trivial to implement if you still would like to add this.
