### ISSUE TITLE
Implicit gevent.monkey.patch_all() considered harmful

### ISSUE THREAD

**Issue by miohtama** [pipermerriam/populus#117]
### What was wrong?

There is an implicit import time `gevent.monkey.patch_all()` in `populus.__init__`.

This is harmful as it might break other libraries within the same Python process, as gevent gives pretty invasive treatment to Python stdlib. Thus, mere action of importing Populus might break your software in subtle ways.

https://github.com/zopefoundation/transaction/issues/21

If gevent event loop and monkey patching is required, I'd suggest to have an explicit init method that the user needs to call.

#### Cute Animal Picture

![aarg](http://i.imgur.com/ZcbRdyJ.jpg)

**Comment by pipermerriam** [comment]
I'm good removing this.  I've since switched over to explicit imports of everything that *needs* monkeypatching so that it's imported from `gevent.*`
