### ISSUE TITLE
Implement `Project` object abstraction

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/populus#122]
### What was wrong?

In the pre `1.0.0` versions of populus there was a command `populus attach` that loaded the user into a python shell with their compiled contracts pre-loaded into the context.  This was removed because of the fragility of the feature and inability to handle the maintenance overhead.

The removal of this feature has left a gap, which is easy access to things like the compiled contracts, a web3 instance, and the `web3.eth.contract` objects.

The proposed way to fix this would be as follows.

```python
>>> from populus.project import default_project as my_project, Project
>>> my_project
<Project at "/path/to/my-project/">  # this would be automatically created an linked to `os.getcwd()`
>>> Project(project_dir="/path/to/some-other-project")
<Project at "/path/to/some-other-project">  # or you can instantiate your own instance if the root project directory is located elsewhere.
>>> my_project.web3  # this would somehow be auto-configured with a test chain or something like that.
>>> my_project.compiled_contracts  # All of the compiled contract data from your project.
{
    "MyContract": {
        "code": "0x...",
        "code_runtime": "0x...",
        "abi": "[...]",
    }
}
>>> contract_factories = project.contract_factories
>>> MyContract = contract_factories.MyContract
>>> MyContract
<web3.contracts.Contract object>
>>> MyContract.deploy()
"0x...."  # The deploy transaction from this contract factory.
```

This is all just in the idea phase.  Feedback welcome.  Please let me know any ways that you think this could be improved.

#### Cute Animal Picture

> put a cute animal picture here.

![dog-shaming17](https://cloud.githubusercontent.com/assets/824194/17493133/3a3ac668-5d6c-11e6-813a-b3c76cddf68b.jpg)

**Comment by euri10** [comment]
sounds like a cool feature
