### ISSUE TITLE
populus deploy and populus chain run return "subprocess.CalledProcessError: Command returned non-zero exit status 1"

### ISSUE THREAD

**Issue by porobov** [pipermerriam/populus#126]
* Populus Version: 1.0.0b4
* OS: Ubuntu 14.04 64 bit

### What was wrong?

Got the same error for commands:
$ populus deploy -d
$ populus chain run

```
(populus) petr@Lenovo-3000-G550:~/Projects/populus$ populus deploy -d
Traceback (most recent call last):
  File "/home/petr/Projects/Venvs/populus/bin/populus", line 11, in <module>
    sys.exit(main())
  File "/home/petr/Projects/Venvs/populus/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/petr/Projects/Venvs/populus/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/petr/Projects/Venvs/populus/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/petr/Projects/Venvs/populus/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/petr/Projects/Venvs/populus/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/petr/Projects/Venvs/populus/local/lib/python2.7/site-packages/populus/cli/deploy_cmd.py", line 113, in deploy
    ensure_account_exists(dry_run_data_dir)
  File "/home/petr/Projects/Venvs/populus/local/lib/python2.7/site-packages/populus/geth.py", line 271, in ensure_account_exists
    accounts = get_geth_accounts(data_dir)
  File "/home/petr/Projects/Venvs/populus/local/lib/python2.7/site-packages/populus/geth.py", line 234, in get_geth_accounts
    raise subprocess.CalledProcessError(1, ' '.join(command))
subprocess.CalledProcessError: Command 'nice -n 20 geth --genesis /home/petr/Projects/Venvs/populus/local/lib/python2.7/site-packages/populus/genesis-test.json --datadir /home/petr/Projects/populus/chains/default --maxpeers 0 --networkid 123456 --port 37285 --ipcpath /tmp/tmpm5cVvH --shh --rpcapi db,eth,net,web3,shh --minerthreads 1 --unlock 0 --password /home/petr/Projects/Venvs/populus/local/lib/python2.7/site-packages/populus/default_blockchain_password --nodiscover account list' returned non-zero exit status 1
```

#### Cute Animal Picture

![Cute baby](i.imgur.com/u9Vcxii.jpg)

**Comment by pipermerriam** [comment]
Can you give me the full output of `pip freeze`?  I suspect you're working with an older version of `py-geth`.

**Comment by porobov** [comment]
It turns out I have populus 0.8.0... sorry for possible misleading.

(populus) petr@Lenovo-3000-G550:~$ pip freeze
argh==0.26.2
bitcoin==1.1.42
cffi==1.7.0
click==6.6
eth-testrpc==0.6.0
ethereum==1.5.2
ethereum-abi-utils==0.2.2
ethereum-client-utils==0.3.2
ethereum-ipc-client==0.1.9
ethereum-rpc-client==0.4.4
ethereum-tester-client==0.9.0
Flask==0.11.1
gevent==1.1.2
greenlet==0.4.10
itsdangerous==0.24
Jinja2==2.8
json-rpc==1.10.3
MarkupSafe==0.23
pathtools==0.1.2
pbkdf2==1.3
populus==0.8.0
py==1.4.31
py-geth==0.9.0
py-solc==0.3.0
pycparser==2.14
pycryptodome==3.4
pyethash==23.1
pysha3==0.3
pytest==2.9.2
PyYAML==3.11
repoze.lru==0.6
requests==2.11.0
rlp==0.4.6
scrypt==0.7.1
secp256k1==0.13.1
six==1.10.0
toposort==1.4
watchdog==0.8.3
web3==1.6.0
Werkzeug==0.11.10

![Cutie](https://i.imgur.com/u9Vcxii.jpg)

**Comment by porobov** [comment]
It is said in this [issue](https://github.com/pipermerriam/populus/issues/49) that I need python-dev. I have just ordinary Python 2.7.12. May it be the case?

**Comment by pipermerriam** [comment]
@porobov It looks like you need to update `py-geth`.  do `pip install py-geth -U --no-deps` and I suspect things will start working.

**Comment by porobov** [comment]
Did it but nothing changed. 

I've also tried to run the geth command from the log. It exits with error: -genesis flag provided but not defined. Geth version: 1.4.10-stable

**Comment by pipermerriam** [comment]
Are you still running a pre 1.0 version of populus?

**Comment by porobov** [comment]
Yes, it's populus 0.8.0

**Comment by pipermerriam** [comment]
Ok, that's the problem.  Pre-populus 1.0 (which only has beta releases right now) the logic that runs `geth` is embedded in the project and has since become outdated with the more recent releases of the `geth` client.  If you run `pip install populus==1.0.0b4` you will get the latest beta release.  Let me know if this fixes things.

**Comment by pipermerriam** [comment]
I want to explicitely point out that `1.0` comes with *significant* breaking changes.  Documentation is still in the works so much of it may not be yet documented.  A somewhat complete list of changes can be found here https://github.com/pipermerriam/populus/issues/104

**Comment by porobov** [comment]
Yes, it works! Well at least it is "Generating DAG" (quite slowly on my machine, but I guess it really means it works, so I'm writing immediately!)). Thank you very much for your time and for your wonderful product. And for the link. Can't wait to start working with it!

**Comment by pipermerriam** [comment]
Happy to help.  Please don't hesitate to reach out if you run into any more problems.

**Comment by pipermerriam** [comment]
Also, I want to point you at #113 which is about to get merged and released in beta5 today.

**Comment by porobov** [comment]
Thank you!
