### ISSUE TITLE
Implement `contract_dirs` (plural)

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/populus#139]
Currently populous only looks in one single directory for contracts.  This is dumb.  You should be able to have a bunch of directories.
- Add ability to configure `contract_dirs` and convert populus to search all of the provided directories.
- Make it so that you can configure this in your `populus.ini`

**Comment by LefterisJP** [comment]
Maybe split this into two issues? Or add two checkpoints. Github makes it look really nice when done so.

1. Allow customization of contracts_dir
2. Allow for multiple such directories to look into

**Comment by pipermerriam** [comment]
I was thinking the same thing.  You're current PR accomplishes this first part.  Just wanted to point you at this issue so you knew it existed.
