### ISSUE TITLE
Allow checksummed addresses to be used in the `populus.ini` file

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/populus#191]
### What was wrong?

Currently if you use a checksummed address in the `populus.ini` file it won't work as expected.  This is because most of the utils do a direct comparison of whether the address as written is present in the list of addresses returned from `eth_accounts`.
### How can it be fixed?

Simplest fix is to find all of the places where address comparisons occur and to ensure that they are being done in a manner that accounts for checksummed addresses.  I think this might actually be a useful function `is_same_address(a, b)` which would take an address in any format (bytes, hex, integer, checksummed, 0x-prefixed or not) and tell you if they are equal.
#### Cute Animal Picture

> put a cute animal picture here.

![tin-man-pet-costume](https://cloud.githubusercontent.com/assets/824194/19003970/8efd41f8-8710-11e6-958f-7d5cbb406ec9.jpg)

**Comment by shravan-shandilya** [comment]
Can I work on this?

**Comment by pipermerriam** [comment]
@shravan-shandilya absolutely.

**Comment by shravan-shandilya** [comment]
@pipermerriam Wouldn't **web3/utils/address.py** a better place for **is_same_address(a, b)**? Need comments.

**Comment by pipermerriam** [comment]
@shravan-shandilya yes, I think `web3.utils.address` would be the appropriate location for this.

**Comment by shravan-shandilya** [comment]
@pipermerriam What would be the next step?

**Comment by pipermerriam** [comment]
Ah, I see, So there a number of places where address comparisons happen such as [here](https://github.com/pipermerriam/populus/blob/master/populus/utils/cli.py#L426)

In those cases we want things to pass even if the address is checksummed.
