### ISSUE TITLE
Populus breaks multiprocessing

### ISSUE THREAD

**Issue by chfast** [pipermerriam/populus#209]
* Populus Version: 1.4.1
* OS: linux

### What was wrong?

Python multiprocessing package stops working when populus is installed. The minimal test is
```
import multiprocessing
def test_mp():
    manager = multiprocessing.Manager()
    scope = manager.dict()
    assert scope
```

#### Cute Animal Picture

![6vbfmik](https://cloud.githubusercontent.com/assets/573380/21313298/545ad004-c5f1-11e6-86e2-f1fc7510e360.jpg)

**Comment by miohtama** [comment]
If this is under py.test this is due to implicit loading of Populus py.test plugin and related gevent monkey patching.

See discussion here:

https://github.com/zopefoundation/transaction/issues/21#issuecomment-237971165

**Comment by pipermerriam** [comment]
This should now be fixed in master.  You can test with `populus==1.5.0-beta.1`
