### ISSUE TITLE
Configuration descriptions

### ISSUE THREAD

**Issue by miohtama** [pipermerriam/populus#216]
### What was wrong?

Currently (master) it is hard to read or understand what goes into 1) config file 2) config objects.

To make this easy to read I suggest more statically typed approach

1. Each config/subconfig/etc. is a Python class

2. All config directives are documented with Sphinx, so you can automatically generate configuration reference  (here is gobbled together example https://websauna.org/docs/reference/templatecontext.html ) 

3. If any adaption needed like converting strings to int the class does parsing

4. When functions take configs they are explicitly annotated

    class ChainConfig(Config):
        """Each chain be configured separate.

        Example:

        .. code-block: yaml

            # Example goes here

        You can also use this from your Python program.
        Here is an example how to set up test-rpc chain:

        .. code-block:: python

            # Example goes here
        """

         # The TCP/IP port where we connect for the JSON-RPC API
         rpc_port = None  # type: int

         def parse(input: dict):
            self.rpc_port = int(input[rpc_port])

    def create_test_chain(config: ChainConfig):
         pass

#### Cute Animal Picture

```

    class ChainConfig(Config):
        """Each chain be configured separate.

        Example:

        .. code-block: yaml

            # Example goes here

        You can also use this from your Python program.
        Here is an example how to set up test-rpc chain:

        .. code-block:: python

            # Example goes here
        """

         # The TCP/IP port where we connect for the JSON-RPC API
         rpc_port = None  # type: int


         def parse(input: dict):
            self.rpc_port = int(input[rpc_port])



    def create_test_chain(config: ChainConfig):
         pass
``´

**Comment by pipermerriam** [comment]
@miohtama I'd be curious to get your feedback on the current docs.

http://populus.readthedocs.io/en/latest/config.html
