### ISSUE TITLE
construct_contract_factories does not work with newer py-solc versions

### ISSUE THREAD

**Issue by 4gn3s** [pipermerriam/populus#223]
* Populus Version: 1.4.2
* OS: linux
* Py-solc Version: 1.0.0

### What was wrong?

When trying to deploy a contract, I get the following error:
> ValueError: Cannot deploy a contract that does not have 'code' associated with it

It seems to be caused by `construct_contract_factories`: the dicts that are passed there have a different format than previously, and contract parameters are not filled correctly.

The error does not occur when I switch back to `py-solc` 0.6

#### Cute Animal Picture

![zebra](http://cdn.attackofthecute.com/October-03-2011-17-05-10-tumblrlhkuweNn801qhcgeyo1500.jpeg)

**Comment by pipermerriam** [comment]
@4gn3s I would pin py-solc to the older version that still works until I'm able to get `populus==1.5.0` released.  I made some breaking changes in `py-solc` recently (which are indicated by the version bump) but populus doesn't have an upper version pinned so fresh installs are grabbing the newer incompatible version.

Alternatively you can install `populus==1.5.0-beta.1` which should not have this issue.  Warning that `1.5.x` line has a new configuration scheme that you'll have to port your `populus.ini` file over to.  Currently no documentation explaining exactly how to do this but i'm happy to help on gitter or here if you want to post your `populus.ini` I'll translate for you.

**Comment by pipermerriam** [comment]
Also that baby zebra is REALLY cute.

**Comment by avatar-lavventura** [comment]
I have installed `py-solc` 0.6 but didn't work on my case :(

**Comment by pipermerriam** [comment]
Can you please provide details on how it isn't working?  Same error?

**Comment by pipermerriam** [comment]
Also it looks like you should be fine with anything up to `py-solc==0.9.1`

**Comment by avatar-lavventura** [comment]
Yes sir same error emerged. I downloaded Version 0.6 from here: https://github.com/pipermerriam/py-solc/tree/v0.6.0 and inside downloaded folder I did: `python setup.py install.`. The error is same on my closed issue but you could also find it here: http://ethereum.stackexchange.com/q/11483/4575. Note: I am so sorry to bother you with this issue. @pipermerriam

**Comment by 4gn3s** [comment]
@avatar-lavventura can you show us the output of the `pip freeze` command in the virtualenv which is used to run populus?

**Comment by avatar-lavventura** [comment]
I guess I was not able to update `py-solc` successfully, any recommendations about how to change its version?   I downloaded Version 0.6 from here: https://github.com/pipermerriam/py-solc/tree/v0.6.0 and inside downloaded folder I did: python setup.py install.

```
[$] pip freeze
bitcoin==1.1.42
cffi==1.9.1
click==6.7
configparser==3.5.0
contextlib2==0.5.4
enum34==1.1.6
eth-testrpc==1.1.0
ethereum==1.6.0
ethereum-abi-utils==0.2.2
gevent==1.1.2
greenlet==0.4.11
idna==2.2
ipaddress==1.0.18
json-rpc==1.10.3
paramiko==2.1.1
pbkdf2==1.3
populus==1.4.2
py==1.4.32
py-geth==1.7.1
py-solc==1.0.0
pycparser==2.17
pycryptodome==3.4.3
pyethash==0.1.27
pylru==1.0.9
pysha3==1.0.0
pytest==3.0.5
PyYAML==3.12
repoze.lru==0.6
requests==2.12.5
rlp==0.4.6
scrypt==0.8.0
secp256k1==0.13.2
toposort==1.5
virtualenv==15.1.0
web3==3.5.2
Werkzeug==0.11.15
```

**Comment by 4gn3s** [comment]
Try `pip install py-solc==0.9.1` in the same place where you did `pip freeze`

**Comment by avatar-lavventura** [comment]
yay! it worked, thanks a lot :1st_place_medal:
