### ISSUE TITLE
Is it possible to call imported Contract or Library using Solidity inside Populus?

### ISSUE THREAD

**Issue by avatar-lavventura** [pipermerriam/populus#226]
- platform darwin -- Python 2.7.12, pytest-3.0.2, py-1.4.31,
- pluggy-0.3.1
- plugins: populus-1.1.0
- OS: Mac OS X
- solc --version: the solidity compiler commandline interface Version: 0.4.8+commit.60cc1668.Darwin.appleclang

Inside my contract I want to use `import`keyword to load other contracts and libraries to make my code more clean and due to this following problem: https://github.com/pipermerriam/populus/issues/221. As an example, I carried [DateTime.sol contract][1] to another file and import it inside myContract file without any problem. 

myContract.sol:

    import "/Users/avatar/populus/contracts/DateTime.sol"; //works.
    contract myContract{
       DateTime date = new DateTime(); //does not work.
       <Some_Code>
    }

But from myContract contract, when I try to call the DateTime contract as: `DateTime date = new DateTime()` I have faced with the following error:

    /usr/local/lib/python2.7/site-packages/populus/chain.py:580: in get_contract
        if contract_name not in self.contract_factories:
    /usr/local/lib/python2.7/site-packages/populus/utils/functional.py:50: in __get__
        res = instance.__dict__[self.name] = self.func(instance)
    /usr/local/lib/python2.7/site-packages/populus/chain.py:198: in contract_factories
        compiled_contracts = self.project.compiled_contracts
    /usr/local/lib/python2.7/site-packages/populus/project.py:153: in compiled_contracts
        optimize=True,
    /usr/local/lib/python2.7/site-packages/populus/compilation.py:42: in compile_project_contracts
        compiled_sources = compile_files(contract_source_paths, **compiler_kwargs)
    /usr/local/lib/python2.7/site-packages/solc/main.py:129: in compile_files
        **kwargs
    /usr/local/lib/python2.7/site-packages/solc/utils/string.py:91: in inner
        return force_obj_to_text(fn(*args, **kwargs))
    
    E Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
    E std::exception::what: std::exception
    E [dev::tag_comment*] = Compiled contract not found.
  
But when the `DateTime contract` was embedded inside `myContract.sol` file, I was able to call `DateTime date = new DateTime();` from `myContract` contract without having any problem. I have used following approach: [How to call a Contract from an existing contract approach][2]. 

myContract.sol:

    contract myContract{
       DateTime date = new DateTime(); //works now.
       <Some_Code>
    }
    contract DateTime{
       <Some_Code>
    }

[Q] I have tried this approach on Solidity Browser and it works. How could I fix this on Populus?

Thank you for your time and help.

<img width="541" alt="screen shot 2017-01-20 at 15 01 21" src="https://cloud.githubusercontent.com/assets/18537398/22148804/f67d7ec8-df18-11e6-8654-335f366d098e.png">

  [1]: https://github.com/pipermerriam/ethereum-datetime
  [2]: http://ethereum.stackexchange.com/a/10483/4575

**Comment by pipermerriam** [comment]
If I understand correctly I believe this is a solidity issue.  My brief experiments show that both of these methods should work fine.  But, I do think I know what is happening.  Read onto Test C for why you're getting an error.

### Test A: separate files

Two files `A.sol` and `B.sol`.

```javascript
// A.sol
pragma solidity ^0.4.0;

import "./B.sol";

contract A {
    B b = new B();

    function dothat() returns (bool) {
        return false;
    }
}
```

```javascript
// B.sol
pragma solidity ^0.4.0;

contract B {
    function doit() returns (bool) {
        return true;
    }
}
```

And compiling them directly with `solc`.

```bash
$ solc tmp/A.sol tmp/B.sol --bin --optimize

======= A =======
Binary:
60606040526040516089806100c783396040519101819003906000f080156100005760008054600160a060020a031916600160a060020a039290921691909117905534610000575b6072806100556000396000f300606060405263ffffffff60e060020a600035041663be4cf1ea81146022575b6000565b34600057602c6040565b604080519115158252519081900360200190f35b60005b905600a165627a7a72305820e5e66f2b70ebb515d1cb16b38e4e362fecd92d0a6c240e9d24c3449862e7eaf700296060604052346000575b6072806100176000396000f300606060405263ffffffff60e060020a6000350416634d536fe381146022575b6000565b34600057602c6040565b604080519115158252519081900360200190f35b60015b905600a165627a7a72305820bb8eba7156ccb8b5c1bc2edfc7734c4848296519038b4b6521ad94cbb0fef1f10029

======= B =======
Binary:
6060604052346000575b6072806100176000396000f300606060405263ffffffff60e060020a6000350416634d536fe381146022575b6000565b34600057602c6040565b604080519115158252519081900360200190f35b60015b905600a165627a7a72305820bb8eba7156ccb8b5c1bc2edfc7734c4848296519038b4b6521ad94cbb0fef1f10029
```

### Test B: same file.

One single file `A.sol`

```javascript
// A.sol
pragma solidity ^0.4.0;

contract A {
    B b = new B();

    function dothat() returns (bool) {
        return false;
    }
}

contract B {
    function doit() returns (bool) {
        return true;
    }
}
```

And compiling them directly with `solc`.

```bash
$ solc tmp/A.sol --bin --optimize

======= A =======
Binary:
60606040526040516089806100c783396040519101819003906000f080156100005760008054600160a060020a031916600160a060020a039290921691909117905534610000575b6072806100556000396000f300606060405263ffffffff60e060020a600035041663be4cf1ea81146022575b6000565b34600057602c6040565b604080519115158252519081900360200190f35b60005b905600a165627a7a72305820f291e5e4279b4062bbfab1fb897bedba1acde9b4eb752085f5a24555b581f5c800296060604052346000575b6072806100176000396000f300606060405263ffffffff60e060020a6000350416634d536fe381146022575b6000565b34600057602c6040565b604080519115158252519081900360200190f35b60015b905600a165627a7a723058201d167fe57930c82b4b58c9a65afde23762f018dd7b2b0adb20911bf3362220720029

======= B =======
Binary:
6060604052346000575b6072806100176000396000f300606060405263ffffffff60e060020a6000350416634d536fe381146022575b6000565b34600057602c6040565b604080519115158252519081900360200190f35b60015b905600a165627a7a723058201d167fe57930c82b4b58c9a65afde23762f018dd7b2b0adb20911bf3362220720029
```

### Test C: same file with `B.sol` still left around and being compiled.

One single file `A.sol` but `B.sol` is still around and being passed into the compiler.

```javascript
// A.sol
pragma solidity ^0.4.0;

contract A {
    B b = new B();

    function dothat() returns (bool) {
        return false;
    }
}

contract B {
    function doit() returns (bool) {
        return true;
    }
}
```

And `B.sol` is still around but just not imported.

```javascript
// B.sol
pragma solidity ^0.4.0;

contract B {
    function doit() returns (bool) {
        return true;
    }
}
```

And compiling them directly with `solc`.

```bash
Internal compiler error during compilation:
/tmp/solidity-20170119-40717-1divfel/solidity_0.4.8/libsolidity/codegen/CompilerContext.cpp(76): Throw in function const eth::Assembly &dev::solidity::CompilerContext::compiledContract(const dev::solidity::ContractDefinition &) const
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: std::exception
[dev::tag_comment*] = Compiled contract not found.
```

I don't exactly understand *why* this is happning but it appears to be caused by there being two contracts named `B`.  Try renaming one of the contracts and see if things work.
