### ISSUE TITLE
populus: How to have multiple transactions in a single block?

### ISSUE THREAD

**Issue by avatar-lavventura** [pipermerriam/populus#238]
- platform darwin -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
- plugins: populus-1.1.0
- OS: Mac OS X

My goal is to write a test case to simulate my contract inside `populus`. I observe that each `transaction()`(even it is a empty function call) will increment block number as one no matter what. 

[Q] As we know in a single block there could be multiple transactions. Is it possible to have multiple transactions in a single block, inside the test case of populus?

 test.py:

    blkArrayIndex =  0;
    gasUsed       = [];
    blockNumber   = [];

    set_txn_hash     = my_contract.transact().dummy(); #this is a dummy transaction.
    contract_address = unmigrated_chain.wait.for_receipt(set_txn_hash)

    gasUsed.append( contract_address["gasUsed"] );
    blockNumber.append( contract_address["blockNumber"] );
    blkArrayIndex = blkArrayIndex + 1;

    set_txn_hash     = my_contract.transact().dummy(); #added line.#
    set_txn_hash     = my_contract.transact().dummy(); #added line.#
    set_txn_hash     = my_contract.transact().dummy(); #added line.#
    set_txn_hash     = my_contract.transact().dummy(); #this is a dummy transaction.
    contract_address = unmigrated_chain.wait.for_receipt(set_txn_hash);

    gasUsed.append( contract_address["gasUsed"] );
    blockNumber.append( contract_address["blockNumber"] );
    blkArrayIndex = blkArrayIndex + 1;

    for j in range(0, blkArrayIndex):
        print '%s:%d |%s: %d' % ("gasUsed", gasUsed[j], "blockNumber", blockNumber[j])

Output (without added lines):

    gasUsed:222648 |blockNumber: 4
    gasUsed:290051 |blockNumber: 5

Output (when new lines are added): block number changed from 5 to 8.

    gasUsed:222648|blockNumber: 4
    gasUsed:350051|blockNumber: 8 <= after the added lines I want block number as 5 instead of 8.

Thank you for your valuable time and help.

<img width="499" alt="screen shot 2017-02-03 at 06 04 33" src="https://cloud.githubusercontent.com/assets/18537398/22578277/38e9df60-e9d0-11e6-8a93-e4d99eeec890.png">

**Comment by miohtama** [comment]
In `testrpc`, by design, each transaction is immediately mined so you do not need to wait 14 seconds. You can switch using Go Ethereum (geth) as the testing backend. It is much more cumbersome to setup and slow. Only reason you'd like to do is to test compatibility for the real Ethereum network.

Furthermore EVM doesn't care if the transactions are in the same block, or different blocks. Everything is procesed sequantially. Unless you use `msg.block` in your contract code this should not be an issue.

**Comment by avatar-lavventura** [comment]
Thanks @miohtama. I understand it better now. Sorry I did not get it, what problems may arise if I use `msg.block`?

**Comment by miohtama** [comment]
@avatar-lavventura It is very unlike you run into problems, unless you try to problem test cases themselves.
