### ISSUE TITLE
How to return negative values inside {8||16||32} bits in populus?

### ISSUE THREAD

**Issue by avatar-lavventura** [pipermerriam/populus#250]
- platform darwin -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
- plugins: populus-1.1.0
- OS: Mac OS X

When I return `output` on test.py, it returns: '`115792089237316195423570985008687907853269984665640564039457584007913129639679L`' instead of `-1`.

[Q] Is this problem related to `python` or `populus`? How could I fix this problem?

I have following _test.py_:

    def test_receipt(web3, accounts, chain, unmigrated_chain):
        my_contract       = unmigrated_chain.get_contract('NumTest');
        
        set_txn_hash     = my_contract.transact().NumTest();
        contract_address = unmigrated_chain.wait.for_receipt(set_txn_hash)
    
        output           = my_contract.call().number();
        print(output);

I have following contract _NumTest.sol_:

    pragma solidity ^0.4.6;    
    contract NumTest {  
        int8 i;    
        function NumTest() {
            i = -1;
        }    
        function number() constant returns (int8 num) {
            return i;    
        }
    }

Thank you for your valuable time and help.

<img width="642" alt="screen shot 2017-02-09 at 13 39 03" src="https://cloud.githubusercontent.com/assets/18537398/23209456/f263dbd6-f901-11e6-9d95-6a2ce7f2f240.png">

**Comment by pipermerriam** [comment]
I am *pretty* sure this is a pyethereum bug.  Will post some more information later today when I confirm and find the other threads/issues that have come up related to this.

**Comment by pipermerriam** [comment]
Ok, not a pyethereum bug.  Fix for this is going to however come in upstream in the `eth-abi-utils` library as this is something that isn't part of populus.  I'll let you know when it's fixed.

**Comment by pipermerriam** [comment]
This is now fixed in `populus>=1.5.3` (via some downstream changes).  You can also just upgrade to `ethereum-abi-utils>=0.4.0`
