### ISSUE TITLE
Instructions for local chain missing

### ISSUE THREAD

**Issue by miohtama** [pipermerriam/populus#257]
### What was wrong?

Local chains are described here http://populus.readthedocs.io/en/latest/chain.html#local-chains

However how one should create one is left as an undocumented exercise to the reader.

#### Cute Animal Picture

```
   / \__
  (    @\___
  /         O
 /   (_____/
/_____/   U
```

**Comment by PJUllrich** [comment]
Does the section **Setting up _local_ chain** in [Tutorial - Part 2](http://populus.readthedocs.io/en/latest/tutorial.part-2.html#setting-up-a-local-chain) help you?

**Comment by pipermerriam** [comment]
@miohtama current discussion around this between myself and @Aviah is that populus is going to move away from chain management.
