### ISSUE TITLE
 binascii.Error: Non-hexadecimal digit found on py.test

### ISSUE THREAD

**Issue by ice09** [pipermerriam/populus#277]
* Populus Version: latest version
* OS: Ubuntu 16.04 LTS

### What was wrong?

compiling a contract worked even with solc 0.4.10. 
Test afterwards break immediately with (can attach more if necessary):

 binascii.Error: Non-hexadecimal digit found

    return _decode_hex(strip_0x(value))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s = b'6060604052341561000c57fe5b5b60008054600160a060020a03191633600160a060020a03161790555b5b610cba806100396000396000f30060...55600101610c73565b5090565b905600a165627a7a723058206c0e9f3128be5394d3f983209bb8e562e5700650ba76c624a178c40e5a7839680029'

    def decode_hex(s):
        if isinstance(s, str):
            return bytes.fromhex(s)
        if isinstance(s, bytes):
>           return binascii.unhexlify(s)
E           binascii.Error: Non-hexadecimal digit found

../env/lib/python3.5/site-packages/rlp/utils_py3.py:50: Error
=========================== 2 failed in 0.46 seconds ===========================

#### Cute Animal Picture

sorry, no really cute free one found...

**Comment by pipermerriam** [comment]
> sorry, no really cute free one found...

I have a really hard time believing that.

Populus is current not compatible with solc `0.4.9` or `0.4.10`.    See https://github.com/ethereum/solidity/issues/1645

I recommend downgrading to `0.4.8`.  I've been told that the next solidity release should have this issue fixed.

Piper

**Comment by Mrdynamic-soni** [comment]
i am also facing same issue while completing cryptography challenge 4, A latge file being read and  Detect single-character XOR
my code::
[[[
    import binascii
with open("crypto_challenge.txt") as infile:
    for line in infile:
        str = binascii.unhexlify(line)
        print(str)
]]]

error::   "binascii.Error: Non-hexadecimal digit found"



please help me
