### ISSUE TITLE
Support looking up libraries from import remapped package

### ISSUE THREAD

**Issue by miohtama** [pipermerriam/populus#298]
* Populus Version: 1.6.6
* OS: OSX

### What was wrong?

Currently, the compiler providers support for using import aliasing to look up contracts from the other packages. This can be done via passing import remapping option to `solc`:

      "compilation": {
        "contracts_source_dir": "./contracts",
        "settings": {
          "optimize": true,
          "import_remappings": ["zeppelin=zeppelin", "ico=ico"]
        }
      },

However, even though compiling works fine and testing framework fines, these contracts cannot be deployed if libraries are being used within the import remappd contracts. This is because Populus contract deployer looks libraries only within the `contracts_source_dir`. 

Suggested possible solutions

* Support a list of paths in `contracts_source_dir` - so that we can have multiple contracts packages where Populus looks for contracts

* Resolve libraries using import remapping, like solc does internally, so that library contracts can be found from other packages

As this is a little bit complex issue, I am not sure how this should be tackled.

#### Cute Animal Picture

```
  /\     /\
  {  `---'  }
  {  O   O  }
  ~~>  V  <~~
   \  \|/  /
    `-----'__
    /     \  `^\_
   {       }\ |\_\_   W
   |  \_/  |/ /  \_\_( )
    \__/  /(_E     \__/
      (  /
       MM
```

**Comment by pipermerriam** [comment]
fixed in #314
