### ISSUE TITLE
Difficulties in starting a ropsten chain

### ISSUE THREAD

**Issue by Netherdrake** [pipermerriam/populus#311]
First of all, I would like to thank you Piper for making the awesome Python libraries for Eth. It has made my life so much easier, and I absolutely love the stack.

I am unfortunately a bit stuck with the deployment step.

I have tried starting a local ropsten network:
```
% populus chain run ropsten
b'WARN [07-13|16:57:42] No etherbase set and no accounts found as default'
b'INFO [07-13|16:57:42] Starting peer-to-peer node               instance=Geth/v1.6.7-stable-ab5646c5/darwin-amd64/go1.8.3'
b'INFO [07-13|16:57:42] Allocated cache and file handles         database=/Users/user/Library/Ethereum/ropsten/geth/chaindata cache=128 handles=1024'
b'INFO [07-13|16:57:42] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Metropolis: 9223372036854775807 Engine: ethash}"'
b'INFO [07-13|16:57:42] Disk storage enabled for ethash caches   dir=/Users/user/Library/Ethereum/ropsten/geth/ethash count=3'
b'INFO [07-13|16:57:42] Disk storage enabled for ethash DAGs     dir=/Users/user/.ethash                              count=2'
b'INFO [07-13|16:57:42] Initialising Ethereum protocol           versions="[63 62]" network=3'
b'INFO [07-13|16:57:42] Loaded most recent local header          number=0 hash=d4e567\xe2\x80\xa6cb8fa3 td=17179869184'
b'INFO [07-13|16:57:42] Loaded most recent local full block      number=0 hash=d4e567\xe2\x80\xa6cb8fa3 td=17179869184'
b'INFO [07-13|16:57:42] Loaded most recent local fast block      number=0 hash=d4e567\xe2\x80\xa6cb8fa3 td=17179869184'
b'INFO [07-13|16:57:42] Starting P2P networking'
b'INFO [07-13|16:57:44] UDP listener up                          self=enode://4324dfeeb47df6b33a590f81e21407b8eeaef79a0d231b70dbe30ed2312f3bff0780f7561b45d1f740933b1358329056aa88f1bf19991475ab89e1debd710bae@192.168.1.101:30303'
b'INFO [07-13|16:57:44] RLPx listener up                         self=enode://4324dfeeb47df6b33a590f81e21407b8eeaef79a0d231b70dbe30ed2312f3bff0780f7561b45d1f740933b1358329056aa88f1bf19991475ab89e1debd710bae@192.168.1.101:30303'
b'INFO [07-13|16:57:44] IPC endpoint opened: /Users/user/Library/Ethereum/ropsten/geth.ipc'
b'INFO [07-13|16:57:44] Mapped network port                      proto=udp extport=30303 intport=30303 interface="UPNP IGDv1-IP1"'
b'INFO [07-13|16:57:44] Mapped network port                      proto=tcp extport=30303 intport=30303 interface="UPNP IGDv1-IP1"'
```

The chain doesn't seem to be syncing (there is no additional output as to what I've pasted above).

The second issue is that `web3` won't connect to the node. 
```
In [1]: ipc_path = '/Users/user/Library/Ethereum/ropsten/geth.ipc'

In [2]: from web3 import Web3, KeepAliveRPCProvider, IPCProvider

In [3]: web3 = Web3(IPCProvider())

In [4]: web3.admin.nodeInfo
....
FileNotFoundError: [Errno 2] No such file or directory

In [5]: web3.isConnected()
Out[5]: False
```

![](http://www.welikeviral.com/files/2014/10/animal-fails-8.gif)

**Comment by pipermerriam** [comment]
OMG, that's an amazing animal picture.  Best I've seen in a while.

**Comment by Netherdrake** [comment]
If I just run `geth --testnet`, it starts syncing.

**Comment by pipermerriam** [comment]
@Netherdrake what version of `go-ethereum`?

**Comment by Netherdrake** [comment]
```
% geth version
Geth
Version: 1.6.7-stable
Git Commit: ab5646c532292b51e319f290afccf6a44f874372
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.8.3/libexec
```

**Comment by pipermerriam** [comment]
Ok, one thing that I see is that you need to specify the IPC path explicitly when you instantiate web3.

```python
Web3(IPCProvider('/Users/user/Library/Ethereum/ropsten/geth.ipc'))
```

This should fix your web3 connection.  As for why syncing isn't occuring, still looking into that.

**Comment by Netherdrake** [comment]
The `geth --testnet` creates an IPC at /Users/user/Library/Ethereum/**testnet**/geth.ipc.
I tried overriding it with this dirty hack, but I still get the timeout error:

```
from populus import Project
project = Project()

# overload ipc path
project.config['chains']['ropsten']['web3.providers.settings.ipc_path'] = \
    '/Users/user/Library/Ethereum/testnet/geth.ipc'

with project.get_chain('ropsten') as chain:
    print('coinbase:', chain.web3.eth.coinbase)
```

Do I need to wait for the geth to finish syncing before I can connect?

**Comment by pipermerriam** [comment]
@Netherdrake as much as I hate to admit it, I think that this may just be broken at some fundamental level that's going to take longer for me to sort out.  I suspect something is going on with how the process is being run that is causing it to hang.  You can get around this by modifying your config file so that the `Ropsten` chain uses the chain class `populus.chain.external.ExternalChain`.  Then under the web3 configuration for that chain, declare the appropriate IPC path and run the chain yourself.  Not ideal but it should be a viable workaround for the time being.

**Comment by Netherdrake** [comment]
It worked like a charm. First contract successfully deployed on a testnet.

Thank you Piper

**Comment by pipermerriam** [comment]
We're talking about moving away from having populus run your chain for you.  It's been consistently fragile and it's a ton of work to provide a decent API to allow you to run the chain in a non-default configuration.  Glad the work-around fixed things.  Lemme know if you have other issues.
