### ISSUE TITLE
Better reporting when `deploy_contract` with value to non-payable constructor

### ISSUE THREAD

**Issue by djrtwo** [pipermerriam/populus#316]
### What was wrong?

I found that in testing, if I execute`provider.get_or_deploy_contract("Contract", {"value": 10})` to a contract constructor that is not payable like  `function Contract() { }`, the error reporting is not helpful. You essentially get a "TransactionFailed" and a deep stack trace to "/Library/Python/2.7/site-packages/ethereum/tester.py:296: TransactionFailed"

I'd like to make the error message a bit more robust in the referenced ethereum/tester.py, but I'm having trouble finding where and in what repo this code lives.

Point me in the right direction and I'll take care of this myself.

Thanks!

#### Cute Animal Picture

![cute animal](http://thewallpaper.co/wp-content/uploads/2016/02/lesser-panda-japan-hd-animal-wallpapers-pet-love-cool-animals-desktop-images-animal-world-windows-desktop-images-lovely-freedom-1805x1015.jpg)

**Comment by djrtwo** [comment]
I'm realizing that maybe it is not so straightforward to get what is going on at that level.
Where in the stack do you think this could/should be caught and given as feedback to the user?

**Comment by pipermerriam** [comment]
@djrtwo in the `web3.py` codebase.  I think a strategy to investigate would be to catch the `TransactionFailed` and then investigate whether the method being called is `payable` and then re-raise something with a better error if you're convinced that you can reliably differentiate.]

Closing as this belongs in the web3.py codebase.

**Comment by djrtwo** [comment]
Thanks! Trying to save a future dev an hour of pulling their hair out...
