### ISSUE TITLE
Switch to `ctoolz` library.

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/populus#320]
### What was wrong?

The `toolz` library is pretty awesome, but it is all pure python and thus, as slow as other pure python *stuff*.

Turns out there is a c implementation of the entire library!  https://pypi.python.org/pypi/cytoolz

### How can it be fixed?

Change to use [`ctoolz`](https://pypi.python.org/pypi/cytoolz)

**Comment by PJUllrich** [comment]
Can this Issue be closed? Otherwise, I'd have a look at it.

**Comment by pipermerriam** [comment]
I believe it's *almost* all done.  There was a hanging `cytoolz` bug with `compose` not being able to be used with a `functools.partial`.

**Comment by pipermerriam** [comment]
@PJUllrich going ahead and closing as the hanging issue will get cleaned up *one of these days*
