### ISSUE TITLE
Cannot deploy contract. Gas too hight

### ISSUE THREAD

**Issue by gelinger777** [pipermerriam/populus#329]
* Populus Version: 1.6.8
* OS: linux

pip freeze
adium-theme-ubuntu==0.3.4
alabaster==0.7.10
anyconfig==0.9.1
argh==0.26.2
astroid==1.4.4
attrs==16.0.0
Babel==2.4.0
beautifulsoup4==4.4.1
bitcoin==1.1.42
blinker==1.3
boto==2.38.0
cffi==1.9.1
chardet==2.3.0
click==6.7
colorama==0.3.9
contextlib2==0.5.4
cryptography==1.3.4
cssselect==0.9.1
debtags==2.0
decorator==4.0.6
defer==1.0.6
dirspec==13.10
Django==1.8.7
dnspython==1.12.0
docutils==0.13.1
duplicity==0.7.6
ecdsa==0.13
Electrum==2.8.3
Electrum-LTC==2.6.4.2
enum34==1.1.6
eth-testrpc==1.1.1
ethereum==1.6.1
ethereum-abi-utils==0.4.0
ethereum-utils==0.2.0
functools32==3.2.3.post2
gyp==0.1
html5lib==0.999
httplib2==0.9.1
idna==2.1
imagesize==0.7.1
ipaddress==1.0.17
ipython==2.4.1
Jinja2==2.9.6
json-rpc==1.10.3
jsonrpclib==0.1.7
jsonschema==2.6.0
Labyrinth==0.6
lazy-object-proxy==1.2.1
lockfile==0.12.2
logilab-common==1.1.0
ltc-scrypt==1.0
lxml==3.6.0
MarkupSafe==1.0
meld==3.14.2
mercurial==3.7.3
mysql-connector-python==2.0.4
mysql-utilities==1.6.1
mysqlclient==1.3.7
ndg-httpsclient==0.4.0
numpy==1.11.0
oauthlib==1.0.3
oneconf==0.3.9
PAM==0.4.2
paramiko==1.16.0
parsel==1.0.2
pathtools==0.1.2
pbkdf2==1.3
pdfshuffler==0.6.0
pexpect==4.0.1
Pillow==3.1.2
piston-mini-client==0.7.5
populus==1.6.8
protobuf==2.6.1
ptyprocess==0.5
py==1.4.33
py-geth==1.7.1
py-solc==1.0.1
pyaes==1.6.0
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.17
pycrypto==2.6.1
pycryptodome==3.4.5
pycups==1.9.73
pycurl==7.43.0
PyDispatcher==2.0.5
pyethash==0.1.27
pyflakes==1.1.0
Pygments==2.1
pygobject==3.20.0
PyJWT==1.3.0
pylint==1.5.2
pylru==1.0.9
pyodbc==3.0.7
pyOpenSSL==16.0.0
pyPdf==1.13
pyserial==3.0.1
pysha3==1.0.2
PySocks==1.6.7
pysqlite==2.7.0
Pyste==0.9.10
pyTelegramBotAPI==2.1.3
pytest==3.0.7
python-apt==1.1.0b1
python-debian==0.1.27
pytz==2014.10
pyudev==0.16.1
pyxdg==0.25
PyYAML==3.12
qrcode==5.2.2
queuelib==1.4.2
repoze.lru==0.6
requests==2.13.0
rlp==0.4.6
ruamel.ordereddict==0.4.13
ruamel.yaml==0.14.5
Scrapy==1.1.0
scrypt==0.8.0
secp256k1==0.13.2
service-identity==16.0.0
simplegeneric==0.8.1
six==1.10.0
snowballstemmer==1.2.1
software-center-aptd-plugins==0.0.0
Sphinx==1.5.3
sqlparse==0.1.18
toposort==1.5
Twisted==16.4.1
typing==3.6.1
ubuntuone-client-data==14.4
unity-lens-photos==1.0
urllib3==1.13.1
vboxapi==1.0
w3lib==1.15.0
watchdog==0.8.3
web3==3.7.2
Werkzeug==0.12.1
wrapt==1.8.0
wxPython==3.0.2.0
wxPython-common==3.0.2.0
zope.interface==4.3.2

### What was wrong?

Please include information like:
(venv) mymaps@mymaps-ThinkPad-E550:~/Desktop/taza/ico$ 
Web3 provider is RPC connection http://127.0.0.1:8545
Owner address is 0x00d2be7F3866160F900DF954E8f032d20fC11e85
Owner balance is 5.941846552 ETH
Starting MilestonePricing deployment, with arguments  {'_milestones': [1492272000, 10000000000000000, 1492876800, 11000000000000000, 1493481600, 12000000000000000, 1494691200, 13000000000000000]}
Traceback (most recent call last):
  File "/home/mymaps/Desktop/taza/ico/ico/deploy.py", line 64, in deploy_contract
    contract, txhash = chain.provider.deploy_contract(contract_name, deploy_transaction=transaction, deploy_kwargs=kwargs)
  File "/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py", line 154, in deploy_contract
    kwargs=deploy_kwargs,
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 298, in deploy
    txn_hash = cls.web3.eth.sendTransaction(deploy_transaction)
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/web3/eth.py", line 239, in sendTransaction
    transaction=formatted_transaction,
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/transactions.py", line 47, in get_buffered_gas_estimate
    gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/functional.py", line 14, in inner
    value = fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/web3/eth.py", line 282, in estimateGas
    [formatted_transaction],
  File "/usr/local/lib/python3.5/dist-packages/web3/providers/manager.py", line 51, in request_blocking
    raise ValueError(response["error"])
ValueError: {'data': 'Internal("Requires higher than upper limit of 1000000000000")', 'code': -32015, 'message': 'Transaction execution error.'}

* what command you ran

deploy-contracts --deployment-name=testnet --deployment-file crowdsales/example.yml  --address 0x00d2be7F3866160F900DF954E8f032d20fC11e85
* the code that caused the failure

#### Cute Animal Picture

![CuteCat](http://static.boredpanda.com/blog/wp-content/uuuploads/cute-baby-animals-2/cute-baby-animals-2-2.jpg)

**Comment by pipermerriam** [comment]
This is indicative of your contract throwing an exception during deployment.  Ways I have typically debugged this type of error:

* comment out the constructor and try deployment (does it fail?)  (if not come back because it may be something different).
* Incrementally uncomment the constructor function until you find which line fails.

**Comment by pipermerriam** [comment]
If you can provide me with contract source I may be able to help further.

**Comment by gelinger777** [comment]
https://github.com/TokenMarketNet/ico/blob/master/contracts/MilestonePricing.sol  here it is . 
the tool is deploying using Populus via pithon... 
can we chat somehow?

**Comment by pipermerriam** [comment]
@gelinger777 yes, there is a link in the README to the gitter chat room for this project.  I'm available there.
