### ISSUE TITLE
Timeout received from populus deploy --chain horton Greeter

### ISSUE THREAD

**Issue by PJUllrich** [pipermerriam/populus#357]
* Populus Version: 2.0.0a4
* OS: osx

### What was wrong?

I tried to deploy the `Greeter` contract as described in [part 2](http://populus.readthedocs.io/en/v1.10.3/tutorial.part-2.html#deploying-the-contract) of the tutorial.

1. I copied the `horton chain` configuration into my `populus.json` file, which was automatically created when I ran `populus init`. The configuration is similar to the one [in the tutorial](http://populus.readthedocs.io/en/latest/tutorial.part-2.html#setting-up-a-local-chain).

2. I activated my virtual environment (Python 3.6.2) and first ran the command:
`populus chain run horton`, which resulted in **A LOT** of output. However, every now and then a block was mined, which I could see on 
```
INFO [10-05|22:17:42] 🔗 block reached canonical chain          number=46 hash=5f1a46…a55ef7
INFO [10-05|22:17:42] 🔨 mined potential block                  number=51 hash=206255…6b9e1f
```

3. Then, I try to deploy the `Greeter` contract with: `populus deploy --chain horton Greeter`. 
#### Output I expected 
```
$ populus deploy --chain horton Greeter
Beginning contract deployment.  Deploying 1 total contracts (1 Specified, 0 because of library dependencies).

Greeter
Accounts
-----------------
0 - 0xf142ff9061582b7b5f2f39f1be6445947a1f3feb

Enter the account address or the number of the desired account [0xf142ff9061582b7b5f2f39f1be6445947a1f3feb]: 0
Deploying Greeter
Deploy Transaction Sent: 0xd3e6ad1ee455b37bd18703a6686575e9471101fbed7aa21808afd0495e026fe6
Waiting for confirmation...

Transaction Mined
=================
Tx Hash      : 0xce71883741bf4a86e2ca5dd0be5e99888e09888b8a40361a9fb1df81210abe10
Address      : 0x89c2a280a483f45a3d140ef752ffe9c6cd4b57fa
Gas Provided : 433940
Gas Used     : 333940


Verifying deployed bytecode...
Verified contract bytecode @ 0x89c2a280a483f45a3d140ef752ffe9c6cd4b57fa matches expected runtime bytecode
Deployment Successful.
```

#### Output I got
```
(venv) MY_USER$ populus deploy Greeter --chain horton
Traceback (most recent call last):
  File "/Users/.../venv/bin/populus", line 11, in <module>
    sys.exit(main())
  File "/Users/.../venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/.../venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/.../venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/.../venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/.../venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/.../venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/.../venv/lib/python3.6/site-packages/populus/cli/deploy_cmd.py", line 85, in deploy_cmd
    with project.get_chain(chain_name) as chain:
  File "/Users/.../venv/lib/python3.6/site-packages/populus/chain/geth.py", line 119, in __enter__
    self.geth.wait_for_ipc(60)
  File "/Users/.../venv/lib/python3.6/site-packages/geth/process.py", line 172, in wait_for_ipc
    _timeout.check()
  File "/Users/.../venv/lib/python3.6/site-packages/geth/utils/compat/compat_stdlib.py", line 73, in check
    raise self
geth.utils.compat.compat_stdlib.Timeout: 60 seconds
```
#### Possible Explanation
When I run the blockchain with `populus chain run horton`, `geth` uses up one whole CPU Core (uses on average 106% of it). Maybe since I block the CPU core already, the deploy call cannot be executed? This shiny peace of metal has 4 Cores though. 

#### Cute Animal Picture

![](https://media.giphy.com/media/hRzDLerjeYGNq/giphy.gif)

**Comment by PJUllrich** [comment]
Related #361

**Comment by namanyayg** [comment]
Same, but I have the timeout set to 120s for some reason. Is there any way to increase the timeout or to make contract calls faster?

**Comment by pipermerriam** [comment]
@namanyayg and @PJUllrich see the updated docs here: http://populus.readthedocs.io/en/latest/tutorial.part-3.html

Populus is going to move away from managing chains for you.  The docs have been updated to include this change and now show you how to run your own local chains.  I'm going to close this issue.  Please re-open or make a new one if this issue isn't fixed.
