### ISSUE TITLE
Bug in utils wait_for_block_number

### ISSUE THREAD

**Issue by Elfoniok** [pipermerriam/populus#375]
* Populus Version: 1.10.1
* OS: linux

### What was wrong?

`poll_fn=lambda:` web3.blockNumber,
AttributeError: 'Web3' object has no attribute 'blockNumber'`

**Comment by pipermerriam** [comment]
`web3.eth.blockNumber`

**Comment by Elfoniok** [comment]
Why this is closed without PR? or i don't understand something?

**Comment by pipermerriam** [comment]
Sorry, I only glanced at the issue and mis-understood what I was seeing. Re-opening.

**Comment by pipermerriam** [comment]
Fixed and available under `v1.11.1`
