### ISSUE TITLE
gas limit reached issues

### ISSUE THREAD

**Issue by autolycus** [pipermerriam/populus#50]
Hi, 

So I've been playing with your framework some. I've been banging my head against the wall trying to get a very simple contract to run for days. I've finally figured out how to get it work, and I think it may be because you have a very subtle bug in the default contract function "sendTransaction" method. 

On line 62 of the file populus/contracts/function.py, you set the default 'gas' value if no 'gas' parameter is passed in the keyword arguments. You use the "get_max_gas" method which pulls the current gasLimit value from the running geth test chain. In my geth test chain, the "gasLimit" value seems to continuously decline all the time. I don't know why the gasLimit is constantly declining, but it seems to decline after every block.

The issue seems to be that by the time my transaction gets submitted to my test chain, the gasLimit value has declined below the "gas" value that is submitted with the transaction. The geth chain seems to then reject this transaction because it has exceeded the gasLimit. 

Do you observe this behavior? To fix it, I've actually just divided the "get_max_gas" response by 2 and now all my transactions seem to go through perfectly. I realize this isn't a great way to do this. I'm thinking that using the 'solc' compiler's '--gas' option might be a better way to get estimates of the transaction gas requirement. Thoughts?

(As a side note, the VM rejecting transactions when the gas value is greater than gasLimit doesn't make any sense to me. It would seem to me that the more appropriate response, would be use a min function on the VM's gasLimit and the gas value sent in the transaction. Then, if the method would require more gas than the min of these two values, then the transaction should fail, not fail outright even for small low actual gas transactions. Do you have any idea why the geth transaction processing is implemented this way?)

**Comment by pipermerriam** [comment]
What do you think about adjusting that logic to use something like 90% of the max gas value?

I think your idea about trying to get gas hints from the solc compiler is pretty interesting and I'd be very open to getting that implemented.

If you'd like to get a PR in to fix the current implementation to use a value slightly under the max gas I'll get it included in a release for you asap.  Otherwise it could be mid-week before I can really get to this.

**Comment by autolycus** [comment]
Ya - give me a few minutes and I'll submit a pull request for a temporary fix.
