### ISSUE TITLE
Solidity Compiler Tests fail in platforms other than Mac OS X

### ISSUE THREAD

**Issue by autolycus** [pipermerriam/populus#52]
Hi, 

When I attempt to run the unit tests via tox in a Debian-based host, the solidity compiler tests fail because my solc compiler has a slightly different version number and library references. Please see the attached log. 

[py_tox_test_06DEC2015.txt](https://github.com/pipermerriam/populus/files/53299/py_tox_test_06DEC2015.txt)

**Comment by autolycus** [comment]
Sorry one other comment, the "tests/command_line_interface" unit test "test_deployment" can end up failing if the user's path is too long. Basically, geth attempts to create a unix domain socket at the following location:  

"~/src/populus/tests/command_line_interface/projects/test-02/chains/default/geth.ipc"  

but if the path is greater than 108 characters, it will fail to create and bind. Obviously this is problem that there is no ultimate solution to, but you might consider making "command_line_interface" into "cli" to reduce the probability of this happening. It would also allow the unit test directories to match with the same naming convention as the "populus/cli" module in the python source.

**Comment by pipermerriam** [comment]
> the "tests/command_line_interface" unit test "test_deployment" can end up failing if the user's path is too long

Where does the 108 character limit come from?

**Comment by autolycus** [comment]
http://man7.org/linux/man-pages/man7/unix.7.html
From Link:
```
           A UNIX domain socket address is represented in the following
           structure:

           struct sockaddr_un {
               sa_family_t sun_family;               /* AF_UNIX */
               char        sun_path[108];            /* pathname */
           };

          The sun_family field always contains AF_UNIX.  On Linux sun_path is
          108 bytes in size; see also NOTES, below.
```

**Comment by pipermerriam** [comment]
Thanks for this.  I'll get that path shortened.
