### ISSUE TITLE
python setup.py install - Fails on ethereum-ipc-client install

### ISSUE THREAD

**Issue by RCL-Carl** [pipermerriam/populus#62]
When I attempt to run 'python setup.py install' from the repo, it seems to fail on the ethereum-ipc/rpc-client packages:

```
$> git pull origin master 
$> mkdir depl
$> virtualenv depl/pop
$> source depl/pop/bin/activate
$> python setup.py install -v 
...
Installed /home/user/src/populus/depl/pop/lib/python2.7/site-packages/ethereum-1.0.8-py2.7.egg
Searching for ethereum-ipc-client>=0.1.1
Reading https://pypi.python.org/simple/ethereum-ipc-client/
Found link: https://pypi.python.org/packages/any/e/ethereum-ipc-client/ethereum-ipc-client-0.1.0.macosx-10.11-x86_64.tar.gz#md5=c2950da8a0fda05253cc7fa70f73df68
Found link: https://pypi.python.org/packages/any/e/ethereum-ipc-client/ethereum-ipc-client-0.1.1.macosx-10.11-x86_64.tar.gz#md5=8fd7db4d539ce1d700fd15d17438c5c9
Found link: https://pypi.python.org/packages/any/e/ethereum-ipc-client/ethereum-ipc-client-0.1.2.macosx-10.11-x86_64.tar.gz#md5=aa5134ac45149483828809f8be92729b
Found link: https://pypi.python.org/packages/source/e/ethereum-ipc-client/ethereum-ipc-client-0.1.0.tar.gz#md5=fc9ce05a79a399ef131028233f63f71e
Found link: https://pypi.python.org/packages/source/e/ethereum-ipc-client/ethereum-ipc-client-0.1.1.tar.gz#md5=57efbe5c2883618798fb6388e8016226
Found link: https://pypi.python.org/packages/source/e/ethereum-ipc-client/ethereum-ipc-client-0.1.2.tar.gz#md5=4a5727fe1bc27986f47239720a66fc7f
Best match: ethereum-ipc-client 0.1.2.macosx-10.11-x86-64
Downloading https://pypi.python.org/packages/any/e/ethereum-ipc-client/ethereum-ipc-client-0.1.2.macosx-10.11-x86_64.tar.gz#md5=aa5134ac45149483828809f8be92729b
Validating md5 checksum for /tmp/easy_install-HtEYih/ethereum-ipc-client-0.1.2.macosx-10.11-x86_64.tar.gz
Processing ethereum-ipc-client-0.1.2.macosx-10.11-x86_64.tar.gz
Unpacking . to /tmp/easy_install-HtEYih/.
Unpacking ./Users to /tmp/easy_install-HtEYih/./Users
Unpacking ./Users/piper to /tmp/easy_install-HtEYih/./Users/piper
Unpacking ./Users/piper/python-environments to /tmp/easy_install-HtEYih/./Users/piper/python-environments
...
Unpacking ./Users/piper/python-environments/eth-ipc-client/lib/python2.7/site-packages/ethereum_ipc_client-0.1.2-py2.7.egg-info/top_level.txt to /tmp/easy_install-HtEYih/./Users/piper/python-environments/eth-ipc-client/lib/python2.7/site-packages/ethereum_ipc_client-0.1.2-py2.7.egg-info/top_level.txt
error: Couldn't find a setup script in /tmp/easy_install-HtEYih/ethereum-ipc-client-0.1.2.macosx-10.11-x86_64.tar.gz
```

If I manually install the ethereum-ipc/rpc-client packages with pip, everything works fine. It does not seem to matter whether I use virtualenv or not. It seems that it is downloading the any package which is a binary distribution from macosx, and then attempts to run the "setup.py" method like it were a source package. 

This was working fine in the 0.6.5 version, but has stopped working now.

**Comment by pipermerriam** [comment]
Thanks for reporting this.  I'll look into it as soon as I get home this
evening.

**Comment by pipermerriam** [comment]
Can you give me a little more information on what system you are on?  linux/osx/win?

Also, I see that you're installing from `python setup.py install`  can you tell me what commit you are on?

Have you tried installing with `pip`?

**Comment by pipermerriam** [comment]
Also, I just pushed/released 0.1.3 of the `ethereum-ipc-client`.  Not anything there related to this but worth noting.

**Comment by RCL-Carl** [comment]
> Can you give me a little more information on what system you are on? linux/osx/win?

Ubuntu 14.04 LTS 

> Also, I see that you're installing from python setup.py install can you tell me what commit you are on?

0.7.2 , git hash: 65644a7839def9

> Have you tried installing with pip?

Pip works fine. However, I'm adding some features that I'm debugging/testing and I usually use "python install setup.py --record files.txt". Out of the box - that doesn't work because it fails as shown. If I manually install ethereum-ipc-client and ethereum-rpc-client with pip - then things work again because pip actually installs from the "wheel" file instead of from the "any" binary package.

**Comment by pipermerriam** [comment]
Hrm.  Not solutions but potentially relevant.

Try setup.py develop

It's how I develop locally.

Second, I think you need to list the filename in the MANIFEST file.

**Comment by RCL-Carl** [comment]
> Try setup.py develop

I followed the same virtualenv setup and then ran: 

```
$> python setup.py develop -v 
```

I get the same problem. If I manually install ethereum-ipc/rpc-client with pip it works fine.

> Second, I think you need to list the filename in the MANIFEST file.

I don't follow. Are referring to "--record files.txt" ? I only use that so that I can run "cat files.txt | xargs rm" to remove the files when I want to. 

-------------------------

I think the issue may have to do with the way you have structured the PyPi repo for the ethereum-ipc/rpc-client projects. Is there a reason you provide the binary "dump" package when the "wheel" package is sufficient to deploy like a binary?

**Comment by pipermerriam** [comment]
Ok, I've just pushed new releases for both clients without the `bdist`.

* https://pypi.python.org/pypi/ethereum-ipc-client/0.1.4
* https://pypi.python.org/pypi/ethereum-rpc-client/0.4.3

Try with those and see if that fixes thing

**Comment by RCL-Carl** [comment]
Yes - that fixes the issue. I can run python setup.py install now and it successfully installs the ipc/rpc clients.
