### ISSUE TITLE
Solc Unit Tests Fail in Ubuntu

### ISSUE THREAD

**Issue by RCL-Carl** [pipermerriam/populus#67]
The unit tests related to the solc compilation fail due to a version number issue of the solc compiler in Ubuntu vs Mac OS X.

Please see the tox log here: 
[build-log.txt](https://github.com/pipermerriam/populus/files/88403/build-log.txt)

**Comment by pipermerriam** [comment]
Ah, yes, the infamous hard-coded version strings from my exact solc build.  Those tests need to be adjusted to be appropriately generic about the version string.  Thanks for reporting this.

**Comment by pipermerriam** [comment]
This should be fixed once #105 is merged.
