### ISSUE TITLE
failures when running tests

### ISSUE THREAD

**Issue by jellegerbrandy** [pipermerriam/populus#69]
I ran the tests and got some failures having to do with starting geth nodes.

[test_output.txt](https://github.com/pipermerriam/populus/files/139219/tmp.txt)

**Comment by pipermerriam** [comment]
I think this failure has to do with the length of the path to the geth.ipc
file being too long.  There is a maximum character limit for the path of
Unix sockets that's relatively short.

**Comment by jellegerbrandy** [comment]
indeed that's the reason, thanks!
