### ISSUE TITLE
Spurious BlockGasLimitReached exceptions while testing

### ISSUE THREAD

**Issue by pjdelport** [pipermerriam/populus#96]
* Populus Version: 0.8.0
* OS: Ubuntu
* `deploy_client_type`: `'ethtester'` (the default)

### What's wrong?

During test runs, some `Function.s()` calls will fail as follows:

```
Traceback (most recent call last):
  […]
  File "[…]/python2.7/site-packages/populus/contracts/functions.py", line 64, in s
    txn_hash = self(*args, **kwargs)
  File "[…]/python2.7/site-packages/populus/contracts/functions.py", line 58, in __call__
    return self.sendTransaction(*args, **kwargs)
  File "[…]/python2.7/site-packages/populus/contracts/functions.py", line 88, in sendTransaction
    **kwargs
  File "[…]/python2.7/site-packages/populus/ethtester_client.py", line 220, in send_transaction
    raise result
BlockGasLimitReached: <Transaction(c400)>: 'gaslimit' actual:6283184 target:3141592
```

(The failing call in question is not big, and nowhere near the block limit in terms of gas usage.)

### Diagnosis

I suspected that the problem is due to the test VM's blocks not being mined frequently enough, causing transactions to pile up in some circumstances until the limit is hit. Inserting an `evm.mine()` call in front of the failing transaction prevents the problem, and seems to confirm this hypothesis.

I haven't been able to diagnose the exact cause leading up to the `BlockGasLimitReached` failures, but I implemented a quick hacky fix in 142070f6: this modifies `populus.ethtester_client.EthTesterClient` to simply perform a `mine()` before each transaction as well as after, which may be overkill, but seems to prevent the problem so far.

#### Cute Animal Picture

![food limit reached](https://s-media-cache-ak0.pinimg.com/564x/b0/43/c8/b043c843fa7c260e3e3707e884d45c10.jpg)

**Comment by pipermerriam** [comment]
Thank you for reporting this.  I am currently getting close to the point where this client will be replaced by `web3.py` (with `ethereum-tester-client` being used under the hood as a provider).  I expect that this is likely to fix the issue given that the standalone version of the tester client has much more thorough tests.

In the meantime, if you were inclined to create a PR that changed the dependency out for `ethereum-tester-client`

**Comment by pipermerriam** [comment]
I'm closing this.  Please re-open if this is still an issue.
